### ISSUE TITLE
Creating mysql tables

### ISSUE THREAD

**Issue by j3k0** [airsdk/apm-repository#2]
I found my way to get the server running (cf the `Dockerfile` pull request). However, next.js / prisma complains that it couldn't find the SQL tables.

```
The table `tag` does not exist in the current database
```

I'm new to this, it looks like the table has to be manually created?

If so, would it be possible to provide an SQL Dump of the database structure? Or maybe it's possible to generate one from the prima.schema file?

**Comment by marchbold** [comment]
Probably looking for 

```
npx prisma db push
```

**Comment by j3k0** [comment]
PR #1 adds a script (`bootsrap`) in `package.json`, that's where I generally look for those kind of things.
